#
# Copyright 2026 Specfuse Contributors
# Licensed under the Apache License, Version 2.0. See LICENSE.
#
"""Tests for the hashed-denylist core (FEAT-2026-0024/T01) in leak_scan.py.

Covers normalize_token, hash_token, load_hashed_denylist, and the
char-sliding-window matcher hashed_denylist_hits. Literals are the
``acme-widget`` placeholder family — never a real private org name — so this
committed test file does not itself leak (see FEAT-2026-0024 PLAN.md and the
leak-scan gate over all tracked files).
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _load_mod():
    path = REPO_ROOT / ".specfuse/scripts/leak_scan.py"
    spec = importlib.util.spec_from_file_location("leak_scan", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["leak_scan"] = mod
    spec.loader.exec_module(mod)
    return mod


_mod = _load_mod()
normalize_token = _mod.normalize_token
hash_token = _mod.hash_token
load_hashed_denylist = _mod.load_hashed_denylist
hashed_denylist_hits = _mod.hashed_denylist_hits

# A placeholder "private literal" and its normalized form. acme-widget-iac ->
# acmewidgetiac (13); acmewidget (10) is the mid-atom-substring case.
_LITERAL = "acme-widget-iac"
_NORM = "acmewidgetiac"
_SALT = "test-salt-0001"


def _build_hashes(literals, salt=_SALT):
    """Mimic T02's generator: normalize each literal, collect lengths + hashes."""
    norms = [normalize_token(x) for x in literals]
    lengths = frozenset(len(n) for n in norms)
    hashes = frozenset(hash_token(n, salt) for n in norms)
    return salt, lengths, hashes


def _write_hashes_file(tmpdir, salt, lengths, hashes, extra_comments=()):
    path = Path(tmpdir) / "leak_denylist.hashes"
    lines = [
        "# leak_denylist.hashes — committed, generated by leak_scan.py.",
        "# Salted SHA-256 of normalized private-org literals. Obfuscation only.",
    ]
    lines.extend(extra_comments)
    lines.append(f"# salt: {salt}")
    lines.append("# lengths: " + ",".join(str(n) for n in sorted(lengths)))
    lines.extend(sorted(hashes))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


class NormalizeTokenTests(unittest.TestCase):
    def test_normalize_lowercases_and_strips_non_alnum(self):
        # AC2: lowercase + keep only [a-z0-9]. Placeholder, not a real org name.
        self.assertEqual(normalize_token("Acme-Widget_IAC"), "acmewidgetiac")

    def test_normalize_preserves_digits(self):
        self.assertEqual(normalize_token("Acme Widget 01!"), "acmewidget01")

    def test_normalize_empty(self):
        self.assertEqual(normalize_token("----"), "")


class HashTokenTests(unittest.TestCase):
    def test_hash_is_deterministic(self):
        # AC3: same input -> same digest.
        self.assertEqual(hash_token(_NORM, _SALT), hash_token(_NORM, _SALT))

    def test_hash_matches_reference_formula(self):
        import hashlib

        expected = hashlib.sha256((_SALT + _NORM).encode("utf-8")).hexdigest()
        self.assertEqual(hash_token(_NORM, _SALT), expected)

    def test_salt_changes_digest(self):
        self.assertNotEqual(hash_token(_NORM, _SALT), hash_token(_NORM, "other"))


class LoadHashedDenylistTests(unittest.TestCase):
    def test_missing_file_returns_empty(self):
        # AC4: absent file -> empty, no crash (mirrors load_denylist).
        salt, lengths, hashes = load_hashed_denylist(
            Path("/nonexistent/leak_denylist.hashes")
        )
        self.assertEqual(salt, "")
        self.assertEqual(lengths, frozenset())
        self.assertEqual(hashes, frozenset())

    def test_well_formed_file_parses(self):
        salt, lengths, hashes = _build_hashes([_LITERAL])
        with tempfile.TemporaryDirectory() as td:
            path = _write_hashes_file(td, salt, lengths, hashes)
            r_salt, r_lengths, r_hashes = load_hashed_denylist(path)
        self.assertEqual(r_salt, _SALT)
        self.assertEqual(r_lengths, frozenset({len(_NORM)}))
        self.assertEqual(r_hashes, hashes)

    def test_extra_comments_are_skipped(self):
        salt, lengths, hashes = _build_hashes([_LITERAL])
        with tempfile.TemporaryDirectory() as td:
            path = _write_hashes_file(
                td, salt, lengths, hashes,
                extra_comments=["# an extra note", "", "#", "   # indented note"],
            )
            r_salt, r_lengths, r_hashes = load_hashed_denylist(path)
        self.assertEqual(r_salt, _SALT)
        self.assertEqual(r_lengths, frozenset({len(_NORM)}))
        self.assertEqual(r_hashes, hashes)


class HashedDenylistHitsTests(unittest.TestCase):
    def test_known_literal_hashes_and_matches(self):
        # AC1 (red on HEAD: helpers absent -> ImportError). Embedded literal flagged.
        salt, lengths, hashes = _build_hashes([_LITERAL])
        line = f"deploy target was {_LITERAL}-prod last night"
        self.assertTrue(hashed_denylist_hits(line, salt, lengths, hashes))

    def test_mid_atom_substring_matches(self):
        # AC5: length-10 'acmewidget' flagged inside length-13 'acmewidgetapp'.
        salt, lengths, hashes = _build_hashes(["acmewidget"])
        self.assertEqual(lengths, frozenset({10}))
        self.assertTrue(
            hashed_denylist_hits("see AcmeWidgetApp config", salt, lengths, hashes)
        )

    def test_clean_token_does_not_match(self):
        # AC5: a non-denylisted token is not flagged. No false positive.
        salt, lengths, hashes = _build_hashes([_LITERAL])
        self.assertFalse(
            hashed_denylist_hits("ordinary commit message", salt, lengths, hashes)
        )

    def test_empty_set_no_match(self):
        # AC5: empty lengths/hashes -> never matches, no crash on any line.
        self.assertFalse(
            hashed_denylist_hits(_LITERAL, "", frozenset(), frozenset())
        )
        self.assertFalse(
            hashed_denylist_hits("", _SALT, frozenset({13}), frozenset({"deadbeef"}))
        )


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
